import React from 'react';
import { ImageResult } from '../types';
import { Loader2, AlertTriangle, Download, Clock, Database } from 'lucide-react';

interface ImageDisplayProps {
  result: ImageResult;
  label: string;
  color: 'red' | 'blue';
}

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ result, label, color }) => {
  const borderColor = color === 'red' ? 'border-archi-red' : 'border-archi-blue';
  const textColor = color === 'red' ? 'text-archi-red' : 'text-archi-blue';

  return (
    <div className="flex flex-col h-full">
      <div className={`flex-grow relative border-4 border-black bg-white rounded-lg overflow-hidden min-h-[300px] flex items-center justify-center group`}>
        {/* Technical Background for Contain Mode */}
        <div className="absolute inset-0 bg-[radial-gradient(#111_1px,transparent_1px)] [background-size:20px_20px] opacity-10"></div>
        
        {/* Technical Label Overlay */}
        <div className={`absolute top-0 left-0 bg-black text-white text-xs font-mono px-2 py-1 z-10`}>
          MODULE_{label.toUpperCase()}
        </div>

        {result.loading ? (
          <div className="flex flex-col items-center gap-4 p-8 animate-pulse relative z-10">
            <Loader2 className={`w-16 h-16 ${textColor} animate-spin`} />
            <div className="font-mono text-sm text-black uppercase tracking-widest">
              PROCESSING_DATA_STREAM...
            </div>
          </div>
        ) : result.error ? (
          <div className="flex flex-col items-center gap-4 p-6 text-center max-w-[80%] relative z-10">
            <AlertTriangle className="w-12 h-12 text-archi-red" />
            <div className="font-mono text-xs text-archi-red font-bold bg-red-100 p-2 border border-archi-red">
              ERROR: {result.error}
            </div>
          </div>
        ) : result.imageUrl ? (
          <>
            <img 
              src={result.imageUrl} 
              alt={`Generated by ${result.modelName}`} 
              className="w-full h-full object-contain relative z-10"
            />
            <a 
              href={result.imageUrl} 
              download={`archigen-${label}.png`}
              className="absolute bottom-4 right-4 bg-archi-black text-white p-2 rounded-full opacity-0 group-hover:opacity-100 transition-opacity hover:scale-110 z-20 shadow-archi-sm"
            >
              <Download size={20} />
            </a>
          </>
        ) : (
          <div className="opacity-20 font-sans text-4xl font-black text-center px-4 text-archi-black relative z-10">
            WAITING FOR INPUT
          </div>
        )}
      </div>

      {/* Tech Specs Panel */}
      <div className="mt-4 border-2 border-black p-3 bg-archi-cream font-mono text-xs grid grid-cols-2 gap-2 shadow-[4px_4px_0px_0px_rgba(0,0,0,0.2)] text-archi-black">
        <div className="flex items-center gap-2 border-b border-black pb-1">
          <Database size={12} />
          <span className="font-bold">MODEL:</span>
        </div>
        <div className="border-b border-black pb-1 truncate" title={result.modelName}>
          {result.modelName}
        </div>
        
        <div className="flex items-center gap-2">
          <Clock size={12} />
          <span className="font-bold">LATENCY:</span>
        </div>
        <div>
          {result.latency > 0 ? `${result.latency}ms` : '--'}
        </div>
      </div>
    </div>
  );
};